"""
Evolution Engine - Self-evolution system for mistake tracking and rule generation
"""

from typing import Dict, Any, List
from pathlib import Path
import json
from datetime import datetime
from collections import defaultdict


class EvolutionEngine:
    """
    Tracks mistakes and auto-generates rules
    """
    
    def __init__(self, config: Dict[str, Any] = None):
        """
        Initialize evolution engine
        
        Args:
            config: Configuration dictionary
        """
        self.config = config or {}
        self.auto_track = self.config.get("auto_track", True)
        self.rule_threshold = self.config.get("rule_threshold", 2)
        
        # Storage for mistake patterns
        self.patterns_file = Path.home() / ".athena" / "mistake_patterns.json"
        self.patterns_file.parent.mkdir(parents=True, exist_ok=True)
        self.patterns = self._load_patterns()
    
    def _load_patterns(self) -> Dict[str, Dict[str, Any]]:
        """Load mistake patterns from file"""
        if self.patterns_file.exists():
            try:
                with open(self.patterns_file, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except:
                return {}
        return {}
    
    def _save_patterns(self):
        """Save mistake patterns to file"""
        try:
            with open(self.patterns_file, 'w', encoding='utf-8') as f:
                json.dump(self.patterns, f, indent=2, ensure_ascii=False)
        except Exception as e:
            print(f"⚠️ Failed to save patterns: {e}")
    
    def track_mistake(
        self,
        pattern: str,
        description: str,
        solution: str,
        category: str = "general",
        threshold: int = None
    ) -> Dict[str, Any]:
        """
        Track a mistake pattern
        
        Args:
            pattern: Mistake pattern identifier
            description: Description of the mistake
            solution: Solution to the mistake
            category: Category (e.g., "critical", "mcp", "general")
            threshold: Threshold for rule generation (default: config value)
            
        Returns:
            Tracking result
        """
        threshold = threshold or self.rule_threshold
        
        # Update pattern count
        if pattern not in self.patterns:
            self.patterns[pattern] = {
                "count": 0,
                "description": description,
                "solution": solution,
                "category": category,
                "first_seen": datetime.now().isoformat(),
                "last_seen": datetime.now().isoformat(),
                "rule_created": False
            }
        
        self.patterns[pattern]["count"] += 1
        self.patterns[pattern]["last_seen"] = datetime.now().isoformat()
        
        # Check if threshold reached
        rule_created = False
        if self.patterns[pattern]["count"] >= threshold and not self.patterns[pattern]["rule_created"]:
            rule_created = self._create_rule(pattern)
            self.patterns[pattern]["rule_created"] = rule_created
        
        # Save patterns
        self._save_patterns()
        
        return {
            "success": True,
            "pattern_tracked": True,
            "rule_created": rule_created,
            "current_count": self.patterns[pattern]["count"],
            "threshold": threshold,
            "message": f"Pattern tracked. Count: {self.patterns[pattern]['count']}/{threshold}"
        }
    
    def _create_rule(self, pattern: str) -> bool:
        """
        Create a rule from mistake pattern
        
        Args:
            pattern: Mistake pattern identifier
            
        Returns:
            True if rule created successfully
        """
        try:
            pattern_data = self.patterns[pattern]
            
            # Create rule file
            rules_dir = Path.home() / ".athena" / "rules"
            rules_dir.mkdir(parents=True, exist_ok=True)
            
            rule_file = rules_dir / f"{pattern.replace(' ', '_')}.md"
            
            rule_content = f"""# Rule: {pattern}

**Description**: {pattern_data['description']}

**Solution**: {pattern_data['solution']}

**Category**: {pattern_data['category']}

**Created**: {datetime.now().isoformat()}

**Pattern Count**: {pattern_data['count']}

---

## Implementation

{pattern_data['solution']}

---

**Auto-generated by Athena Brain Evolution Engine**
"""
            
            with open(rule_file, 'w', encoding='utf-8') as f:
                f.write(rule_content)
            
            print(f"✅ Rule created: {rule_file}")
            return True
        except Exception as e:
            print(f"❌ Failed to create rule: {e}")
            return False
    
    def get_patterns(self) -> Dict[str, Dict[str, Any]]:
        """Get all tracked patterns"""
        return self.patterns
    
    def get_pattern(self, pattern: str) -> Dict[str, Any]:
        """Get specific pattern"""
        return self.patterns.get(pattern, {})

